name: pytest

on: [push, pull_request]

jobs:
  linuxbuild:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip        
          wget https://github.com/sccn/liblsl/releases/download/1.13.0-b13/liblsl-1.13.0-Linux64-bionic.deb
          sudo dpkg -i liblsl-1.13.0-Linux64-bionic.deb        
          pip install git+https://github.com/labstreaminglayer/liblsl-Python.git                         
          pip install numpy
          pip install -r requirements.txt
          pip install .
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pip install coverage
          pip install pytest-cov
          pip install pytest
          pytest
      - name: Cache coverage report
        uses: actions/cache@v2
        id: linux-test
        with:
          path: ./htmlcov
          key: coverage-report

  submit-coveralls:
    runs-on: ubuntu-latest
    needs: [linuxbuild]
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALL_SECRET }}
    steps:
      - name: Download Cache
        uses: actions/cache@v2
        id: linux-test
        with:
          path: ./htmlcov
          key: coverage-report
      - name: Submit Report
        run: |
          export COVERALLS_REPO_TOKEN
          pip install coveralls
          coveralls

  macbuild:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip        
          pip install -r requirements.txt
          pip install .
      - name: Test with pytest
        run: |
          pip install coverage
          pip install pytest-cov
          pip install pytest
          pytest

  winbuild:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
      - name: Test with pytest
        run: |
          pip install coverage
          pip install pytest-cov
          pip install pytest
          pytest
